# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI For Angular

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: [self-hosted, production]

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build
    - run: pwd
    - run: mv /var/www/front-end/cycling_journey_angular /var/www/front-end/cycling_journey_angular_old
      continue-on-error: true
    - run: cp -r ./dist/cycling_journey_angular /var/www/front-end/
